# Generated by Django 3.0.2 on 2020-01-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='instument',
            new_name='instrument',
        ),
    ]
